# Import the LangChain prompt template
from langchain_core.prompts import ChatPromptTemplate

# Import the Gemini LangChain model from the shared LLM module
from utils.llm_client import get_langchain_model

# Import the task lookup tool
from agents.tools import lookup_task

# Import the shared agent state
from agents.agent_state import agent_state


# Create the Gemini model used by the LangChain chain
llm = get_langchain_model()


# Define the structured prompt template for the due-date agent
prompt_template = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
            You are a task management assistant.

            Your role is to suggest an appropriate due date
            for a task based on its title, description, and priority.

            Return only one date in YYYY-MM-DD format.
            """
        ),
        (
            (
            "human",
            """
            Task title: {title}
            Description: {description}
            Priority: {priority}

            Stored task information:
            {task_information}

            Suggest a suitable due date.
            """
)
        )
    ]
)


# Create the LangChain workflow
# The prompt is sent to the Gemini model
due_date_chain = prompt_template | llm



def suggest_due_date(
    title: str,
    description: str = "",
    priority: str = "normal",
    task_id: int | None = None
) -> str:
    """
    Suggest a task due date using LangChain, Gemini,
    the task lookup tool, and internal agent state.

    Args:
        title: The title of the task.
        description: Additional information about the task.
        priority: The priority level of the task.
        task_id: Optional ID used to look up stored task information.

    Returns:
        The due-date suggestion generated by Gemini.
    """

    # Record that a new agent run has started
    agent_state.record_action(
        f"Due date requested for task: {title}"
    )

    # Default information when no stored task is requested
    task_information = "No stored task information available."

    # Use the lookup tool when a task ID is provided
    if task_id is not None:

        task_information = lookup_task.invoke(
            {
                "task_id": task_id
            }
        )

        # Record the tool used by the agent
        agent_state.record_tool_call("lookup_task")

        # Add tool usage to the state history
        agent_state.record_action(
            f"lookup_task called for task ID {task_id}"
        )

    # Send the task information through the LangChain workflow
    response = due_date_chain.invoke(
        {
            "title": title,
            "description": description,
            "priority": priority,
            "task_information": task_information
        }
    )

    # Handle a normal string response
    if isinstance(response.content, str):

        suggestion = response.content.strip()

    # Handle structured Gemini content blocks
    elif isinstance(response.content, list):

        text_parts = []

        for block in response.content:

            if isinstance(block, dict) and "text" in block:
                text_parts.append(block["text"])

            elif isinstance(block, str):
                text_parts.append(block)

        suggestion = "".join(text_parts).strip()

    # Handle any unexpected response type
    else:
        suggestion = str(response.content).strip()

    # Store the final suggestion in agent state
    agent_state.update_suggestion(suggestion)

    # Record successful completion in history
    agent_state.record_action(
        f"Due date suggestion generated: {suggestion}"
    )

    return suggestion