# Import the LangChain prompt template
from langchain_core.prompts import ChatPromptTemplate

# Import the Gemini LangChain model from the shared LLM module
from utils.llm_client import get_langchain_model


# Create the Gemini model used by the LangChain chain
llm = get_langchain_model()


# Define the structured prompt template for the due-date agent
prompt_template = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
            You are a task management assistant.

            Your role is to suggest an appropriate due date
            for a task based on its title, description, and priority.

            Return only one date in YYYY-MM-DD format.
            """
        ),
        (
            "human",
            """
            Task title: {title}
            Description: {description}
            Priority: {priority}

            Suggest a suitable due date.
            """
        )
    ]
)


# Create the LangChain workflow
# The prompt is sent to the Gemini model
due_date_chain = prompt_template | llm


def suggest_due_date(
    title: str,
    description: str = "",
    priority: str = "normal"
) -> str:
    """
    Suggest a task due date using a LangChain prompt and Gemini.

    Args:
        title: The title of the task.
        description: Additional information about the task.
        priority: The priority level of the task.

    Returns:
        The due-date suggestion generated by Gemini.
    """

    # Send the task information through the LangChain workflow
    response = due_date_chain.invoke(
        {
            "title": title,
            "description": description,
            "priority": priority
        }
    )

    # Gemini may return message content as either a string
    # or a list of structured content blocks.
    if isinstance(response.content, str):
        return response.content.strip()

    # Extract text from structured Gemini content blocks
    if isinstance(response.content, list):
        text_parts = []

        for block in response.content:
            # Some LangChain Gemini responses store text
            # inside a dictionary content block
            if isinstance(block, dict) and "text" in block:
                text_parts.append(block["text"])

            # Handle any plain text items returned in the list
            elif isinstance(block, str):
                text_parts.append(block)

        # Combine all extracted text into one clean response
        return "".join(text_parts).strip()

    # Fallback in case an unexpected content type is returned
    return str(response.content).strip()